name: Hoge

on:
  push:
    branches:
      - main

jobs:
  hoge:
    name: Hoge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Sync File
        uses: Redocly/repo-file-sync-action@master
        with:
          GH_PAT: ${{ secrets.PAT_TOKEN }}
          GIT_EMAIL: hirotomo.yamada@avap.co.jp
          GIT_USERNAME: hirotomoyamada
          BRANCH_PREFIX: changeset-release

      - name: Change PR Title
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${{ steps.sync.outputs.BRANCH_NAME }}`
            });

            if (pullRequests.length > 0) {
              const pr = pullRequests[0];
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                title: '新しいタイトル'
              });
            }

      - name: Update File
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'hirotomoyamada',
              repo: 'github-actions-b-trial',
              workflow_id: 'hoge.yml',
              ref: 'main'
            })
